### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by icamps** [ehermes/ased3#1]
Hello,
My box is running Linux Mint 19.1 (a flavor of Ubuntu).

I cloned the repository using
`git clone https://github.com/ehermes/ased3.git`

and then executed:
`python setup.py install`

When installing ASED3, I am facing the following errors:
`gfortran: error: build/temp.linux-x86_64-2.7/ased3/_d3params.o: No such file or directory
gfortran: error: build/temp.linux-x86_64-2.7/ased3/_d3.o: No such file or directory
gfortran: error: build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/ased3/_d3-f2pywrappers2.o: No such file or directory`

If I execute
`python3 setup.py install`

I got:
`build/src.linux-x86_64-3.6/ased3/_d3module.c:17:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
build/src.linux-x86_64-3.6/ased3/_d3module.c:17:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ibuild/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/ased3 -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.6m -c build/src.linux-x86_64-3.6/ased3/_d3module.c -o build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/ased3/_d3module.o -MMD -MF build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/ased3/_d3module.o.d" failed with exit status 1`

Do you have any ideas?

Thanks in advance.

**Comment by ehermes** [comment]
This package is entirely unmaintained. I suggest you use the official ASE wrapper around the reference implementation of dftd3 (I also wrote this wrapper): https://wiki.fysik.dtu.dk/ase/ase/calculators/dftd3.html

My primary reason for creating this `ased3` project was because the reference implementation at the time did not have analytical gradients/stress tensors for threebody terms, a problem that has now been resolved. There should be no reason to use this project.

**Comment by icamps** [comment]
@ehermes Thanks for your answer.

The truth is that I am trying to setting up other tool ([https://github.com/isayev/ASE_ANI]) that uses ASED3 as a dependence. And it written for Python3. So, I need to install ASED3 for it.

**Comment by ehermes** [comment]
Can you show me where ASE_ANI requires ASED3? I should be able to figure out how to make it use ASE's built-in dftd3 wrapper.

I suppose I could take some time today to get this repo working with Python3, but I will warn you that the underlying Fortran is very buggy. I don't think I ever managed to get it to compile with gfortran, only with Intel ifort.

**Comment by icamps** [comment]
I really do not know where ASE_ANI implemented the use of ASED3. I installed it, then, when running the installation test, it complains about needing to install ASED3. I wrote to the ASE_ANI developer and he only said that the use of ASED3 is optional, but did not give me the option to "disable" its use.

I appreciate your effort. Thank you very much.

**Comment by ehermes** [comment]
The issue was that the build options assumed you were using ifort. I changed the build options to assume gfortran instead, since that's more common.
